"""Generate vim-visionbasic/autoload/visionbasic.vim from the plugin database."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
import vbdb

OUT = REPO + "/autoload/visionbasic.vim"

db = vbdb.load()
GROUP_LABEL = {gid: label for gid, label, _ in vbdb.groups(db)}


def vstr(text):
    """A single-quoted Vim string literal."""
    return "'" + str(text).replace("'", "''") + "'"


def entry(kw):
    d = {
        "g": vstr(GROUP_LABEL[kw["group"]]),
        "s": vstr(kw.get("syntax", kw["keyword"])),
        "d": vstr(kw.get("description", "")),
    }
    if kw.get("example"):
        d["e"] = vstr(kw["example"])
    if kw.get("notes"):
        d["n"] = vstr(kw["notes"])
    if kw.get("warning"):
        d["w"] = vstr(kw["warning"])
    if kw.get("parameters"):
        params = []
        for p in kw["parameters"]:
            params.append(
                "[%s, %s, %s, %s]"
                % (
                    vstr(p["name"]),
                    vstr(p.get("range") or p.get("type") or ""),
                    vstr(p.get("description", "")),
                    "1" if p.get("optional") else "0",
                )
            )
        d["p"] = "[" + ", ".join(params) + "]"
    flags = "".join(
        f
        for f, key in (
            ("u", "unimplemented"),
            ("m", "mlSafe"),
            ("M", "mathWarning"),
            ("V", "varNote"),
        )
        if kw.get(key)
    )
    if flags:
        d["f"] = vstr(flags)
    return "{" + ", ".join("%s: %s" % (vstr(k), v) for k, v in d.items()) + "}"


L = []
w = L.append
w('" Vision BASIC keyword database and helper functions.')
w('" Generated from the C64 IDE VisionBASIC %s plugin definition.' % db["version"])
w('" Source: %s' % db["url"])
w('" NOTE: Generated file — regenerate rather than editing by hand.')
w("scriptencoding utf-8")
w("")
w("let s:save_cpo = &cpoptions")
w("set cpoptions&vim")
w("")
w('" ─── Keyword database ────────────────────────────────────────────────────────')
w("let s:db = {}")
for kw in db["keywords"]:
    if kw.get("fragment"):
        continue
    name = vbdb.display(kw["keyword"])
    w("let s:db[%s] = %s" % (vstr(name.upper()), entry(kw)))
w("")
w("let s:mnemonics = [%s]" % ", ".join(vstr(m) for m in db["mnemonics"]))
w("let s:math_note = %s" % vstr(db["notes"]["math"]))
w("let s:var_note = %s" % vstr(db["notes"]["variables"]))
w("")
w('" ─── Public accessors ────────────────────────────────────────────────────────')
w("function! visionbasic#keywords() abort")
w("  return sort(keys(s:db))")
w("endfunction")
w("")
w("function! visionbasic#mnemonics() abort")
w("  return copy(s:mnemonics)")
w("endfunction")
w("")
w('" For a statusline: %{visionbasic#mode()} -> "BASIC" or "ML".')
w("function! visionbasic#mode() abort")
w("  return get(b:, 'visionbasic_ml_mode', 0) ? 'ML' : 'BASIC'")
w("endfunction")
w("")
w("function! visionbasic#lookup(word) abort")
w("  let l:key = toupper(a:word)")
w("  return get(s:db, l:key, {})")
w("endfunction")
w("")
w('" True when the cursor column sits inside a [...] machine language block.')
w("function! visionbasic#in_assembly(line, col) abort")
w("  let l:before = strpart(a:line, 0, a:col)")
w("  return strridx(l:before, '[') > strridx(l:before, ']')")
w("endfunction")
w("")
w('" ─── Documentation rendering ─────────────────────────────────────────────────')
w("function! s:wrap(text, width, indent) abort")
w("  let l:lines = []")
w("  let l:cur = ''")
w("  for l:word in split(a:text, ' ')")
w("    if l:cur !=# '' && strlen(l:cur) + 1 + strlen(l:word) > a:width")
w("      call add(l:lines, a:indent . l:cur)")
w("      let l:cur = l:word")
w("    else")
w("      let l:cur = l:cur ==# '' ? l:word : l:cur . ' ' . l:word")
w("    endif")
w("  endfor")
w("  if l:cur !=# ''")
w("    call add(l:lines, a:indent . l:cur)")
w("  endif")
w("  return l:lines")
w("endfunction")
w("")
w("function! visionbasic#render(word) abort")
w("  let l:key = toupper(a:word)")
w("  let l:e = get(s:db, l:key, {})")
w("  if empty(l:e)")
w("    if index(s:mnemonics, l:key) >= 0")
w("      return [l:key . '  (6502 mnemonic)', '',")
w("        \\ 'Machine language lives inside [] brackets, statements are separated',")
w('        \\ \'by ":", and ";" starts a comment. Branches and jumps may target a\',')
w("        \\ 'BASIC line number directly, e.g. JMP1000.']")
w("    endif")
w("    return []")
w("  endif")
w("  let l:out = [l:e.s, repeat('-', strlen(l:e.s)), '']")
w("  let l:out += s:wrap(l:e.d, 72, '')")
w("  if has_key(l:e, 'p')")
w("    call add(l:out, '')")
w("    call add(l:out, 'Parameters:')")
w("    for l:p in l:e.p")
w("      let l:head = printf('  %-12s %s', l:p[0] . (l:p[3] ? ' (opt)' : ''), l:p[1])")
w("      call add(l:out, l:head)")
w("      let l:out += s:wrap(l:p[2], 56, '        ')")
w("    endfor")
w("  endif")
w("  if has_key(l:e, 'e')")
w("    call add(l:out, '')")
w("    call add(l:out, 'Example:')")
w("    call add(l:out, '  ' . l:e.e)")
w("  endif")
w("  if has_key(l:e, 'n')")
w("    call add(l:out, '')")
w("    let l:out += s:wrap(l:e.n, 72, '')")
w("  endif")
w("  if has_key(l:e, 'w')")
w("    call add(l:out, '')")
w("    let l:out += s:wrap('!! ' . l:e.w, 72, '')")
w("  endif")
w("  let l:f = get(l:e, 'f', '')")
w("  if l:f =~# 'u'")
w("    call add(l:out, '')")
w("    let l:out += s:wrap('!! Not implemented by Vision BASIC.', 72, '')")
w("  endif")
w("  if l:f =~# 'M'")
w("    call add(l:out, '')")
w("    let l:out += s:wrap(s:math_note, 72, '')")
w("  endif")
w("  if l:f =~# 'V'")
w("    call add(l:out, '')")
w("    let l:out += s:wrap(s:var_note, 72, '')")
w("  endif")
w("  if l:f =~# 'm'")
w("    call add(l:out, '')")
w("    call add(l:out, 'ML-safe: usable inside an ASSEM block.')")
w("  endif")
w("  call add(l:out, '')")
w("  call add(l:out, 'Category: ' . l:e.g)")
w("  return l:out")
w("endfunction")
w("")
w('" Show the documentation for the word under the cursor in a preview window.')
w("function! visionbasic#doc(...) abort")
w("  let l:word = a:0 && a:1 !=# '' ? a:1 : expand('<cword>')")
w('  " Pick up the trailing $ or # of CHR$, GET# and friends.')
w("  let l:line = getline('.')")
w("  let l:tail = matchstr(l:line, '\\%' . col('.') . 'c\\k*\\zs[$#]')")
w("  if l:tail !=# '' && has_key(s:db, toupper(l:word . l:tail))")
w("    let l:word .= l:tail")
w("  endif")
w("  let l:text = visionbasic#render(l:word)")
w("  if empty(l:text)")
w("    echohl WarningMsg")
w("    echomsg 'Vision BASIC: no entry for ' . l:word")
w("    echohl None")
w("    return")
w("  endif")
w("  silent! pclose")
w(
    "  execute 'silent! pedit! +setlocal\\\\ buftype=nofile\\\\ bufhidden=wipe\\\\ noswapfile\\\\ nobuflisted [Vision\\\\ BASIC]'"
)
w("  let l:win = win_getid()")
w("  noautocmd wincmd P")
w("  setlocal modifiable")
w("  silent %delete _")
w("  call setline(1, l:text)")
w("  setlocal nomodifiable nomodified filetype=help")
w("  noautocmd call win_gotoid(l:win)")
w("endfunction")
w("")
w('" ─── Completion ──────────────────────────────────────────────────────────────')
w("\" 'omnifunc' — completes 6502 mnemonics inside [] and keywords everywhere else.")
w("function! visionbasic#complete(findstart, base) abort")
w("  if a:findstart")
w("    let l:line = getline('.')")
w("    let l:start = col('.') - 1")
w("    while l:start > 0 && l:line[l:start - 1] =~# '\\a'")
w("      let l:start -= 1")
w("    endwhile")
w("    return l:start")
w("  endif")
w("  let l:asm = visionbasic#in_assembly(getline('.'), col('.') - 1)")
w("  let l:pool = l:asm ? s:mnemonics : keys(s:db)")
w("  let l:out = []")
w("  for l:name in sort(copy(l:pool))")
w("    if l:name !~? '^' . escape(a:base, '\\.*$^~[]')")
w("      continue")
w("    endif")
w("    if l:asm")
w("      call add(l:out, {'word': l:name, 'kind': 'a', 'menu': '6502 mnemonic'})")
w("    else")
w("      let l:e = s:db[l:name]")
w("      call add(l:out, {")
w("        \\ 'word': l:name,")
w("        \\ 'kind': get(l:e, 'f', '') =~# 'u' ? 'x' : 'k',")
w("        \\ 'menu': l:e.s,")
w("        \\ 'info': join(visionbasic#render(l:name), \"\\n\"),")
w("        \\ })")
w("    endif")
w("  endfor")
w("  return l:out")
w("endfunction")
w("")
w('" ─── Keyword case folding ────────────────────────────────────────────────────')
w('" Uppercase Vision BASIC keywords on a line, leaving strings and comments be.')
w("function! visionbasic#uppercase_line(lnum) abort")
w("  let l:line = getline(a:lnum)")
w("  if l:line ==# ''")
w("    return")
w("  endif")
w("  let l:result = ''")
w("  let l:i = 0")
w("  let l:len = strlen(l:line)")
w("  while l:i < l:len")
w("    let l:ch = l:line[l:i]")
w("    if l:ch ==# '\"'")
w('      " Copy the string literal verbatim.')
w("      let l:end = stridx(l:line, '\"', l:i + 1)")
w("      let l:end = l:end < 0 ? l:len - 1 : l:end")
w("      let l:result .= strpart(l:line, l:i, l:end - l:i + 1)")
w("      let l:i = l:end + 1")
w("    elseif l:ch ==# ';'")
w("      let l:result .= strpart(l:line, l:i)")
w("      break")
w("    else")
w("      let l:word = matchstr(l:line, '^\\a[[:alnum:]!@#%&?]*[$#]\\=', l:i)")
w("      if l:word ==# ''")
w("        let l:result .= l:ch")
w("        let l:i += 1")
w("      else")
w("        if toupper(l:word) ==# 'REM'")
w("          let l:result .= 'REM' . strpart(l:line, l:i + 3)")
w("          break")
w("        endif")
w("        let l:up = toupper(l:word)")
w("        let l:known = has_key(s:db, l:up) || index(s:mnemonics, l:up) >= 0")
w("        let l:result .= l:known ? l:up : l:word")
w("        let l:i += strlen(l:word)")
w("      endif")
w("    endif")
w("  endwhile")
w("  if l:result !=# l:line")
w("    call setline(a:lnum, l:result)")
w("  endif")
w("endfunction")
w("")
w("let &cpoptions = s:save_cpo")
w("unlet s:save_cpo")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as fh:
    fh.write("\n".join(L) + "\n")
print("wrote", OUT, len(L), "lines")
